### ISSUE TITLE
Request for clarification: Has this project been abandoned?

### ISSUE THREAD

**Issue by reidhoch** [newrelic/newrelic-kubernetes-operator#145]
We've been searching for a GitOps-y way to deploy monitoring at the same time as we deploy our Kubernetes manifests. This project seems promising, but it is lacking features and does not appear to be actively worked on. Can someone from New Relic confirm or deny whether this is abandonware now?

Thanks,
Reid

**Comment by kidk** [comment]
Hi @reidhoch 

At the moment we don't have the bandwidth to develop this further. That doesn't mean it's completely abandoned, as we are open to any community contributions and will review these. 

Our main focus at the moment is on Terraform where we recently added support for latest Synthetics and Alerting features: https://github.com/newrelic/terraform-provider-newrelic So I would advise Terraform as an alternative.

Once we have caught up with the Terraform work we want to start investing in this again.

**Comment by reidhoch** [comment]
@kidk Thanks for the update, I appreciate your responding so quickly. We're already using the New Relic Terraform provider, so I'll focus my effort there.

**Comment by sirianni** [comment]
+1 my team would also prefer using Kubernetes for GitOps management of NewRelic entities.  

We do use terraform extensively but it's more heavyweight in our setup for managing these sorts of things.  We'd like to be able to define the monitoring entities (alerts, dashboards, etc.)  in the same Helm chart as the application itself and have them deployed and versioned together.
