### ISSUE TITLE
Streamline the development experience

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-kubernetes-operator#24]
### Objective

Developers wishing to get started with this project should have an easy path to get up and running.  Any resources necessary should be public and readily available. 

### Acceptance Criteria
- Documentation is updated for a simple local development process
- Example docker images are available for use
- The initial development process is vetted by a few folks within NR and all DTK team members

### Notes
- No easy way to get kube builder set up
- Running K8s within Docker could use some notes

**Comment by thande** [comment]
I think https://github.com/newrelic/newrelic-kubernetes-operator/pull/39 that I opened addresses most of these points

**Comment by zlesnr** [comment]
I believe this has been resolved.
