### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-kubernetes-operator#25]
### Objective

Ensure the project documentation includes the NR header and footer noting community support, and community resources available for discussion.

### Acceptance Criteria
- README header for NR is included
- README footer for NR is included
- Make sure the standard DTK repo template features have been integrated (badges, banners, etc)
- Documentation is formatted, spell checked, and read for clarity

**Comment by jthurman42** [comment]
Relates to #36

**Comment by sanderblue** [comment]
Resolved in #41 and #44
