### ISSUE TITLE
Rename Policy to AlertPolicy

### ISSUE THREAD

**Issue by dobbs** [newrelic/newrelic-kubernetes-operator#52]
### Feature Description
"Policy" is very overloaded term in the kubernetes ecosystem.

### Describe Alternatives
Other names might be fine, provided they're more specific than Policy.

**Comment by zlesnr** [comment]
This work has been started in https://github.com/newrelic/newrelic-kubernetes-operator/pull/60

**Comment by dobbs** [comment]
The work is largely done with #82
